### ISSUE TITLE
Class not found

### ISSUE THREAD

**Issue by stijnb1234** [emotality/tawk-laravel#2]
Next ErrorException: Class 'Emotality\TawkTo\Facades\TawkTo' not found

**Comment by emotality** [comment]
Hi :)

What Laravel version are you using?

**Comment by stijnb1234** [comment]
Hello.

I'm using version 5.7.14.

**Comment by emotality** [comment]
Weird, should auto discover. 

Please try these commands:

```bash
composer update emotality/tawk-laravel
php artisan package:discover --ansi
composer dump -o
````

If that doesn't work, please add the `TawkTo` facade to your `aliases` array inside `config/app.php` like this:

```
'aliases' => [
    /** other Facades here **/
    'TawkTo' => Emotality\TawkTo\Facades\TawkTo::class,
];
```
