### ISSUE TITLE
Autodump error when generating autodump

### ISSUE THREAD

**Issue by pianistprogrammer** [emotality/tawk-laravel#3]
Using version ^1.1 for emotality/tawk-laravel
./composer.json has been updated
Running composer update emotality/tawk-laravel
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking emotality/tawk-laravel (v1.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Downloading emotality/tawk-laravel (v1.1)
  - Installing emotality/tawk-laravel (v1.1): Extracting archive
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In PackageManifest.php line 122:
                         
  Undefined index: name  
                         

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by emotality** [comment]
This is not an issue with the package, this is an issue with your project.

This fails at `postAutoloadDump` which is AFTER the package installation.

```
In PackageManifest.php line 122:

Undefined index: name
```

It means that one of you packages doesn't have the `name` key in their `composer.json` file.

```
$this->format($package['name'])
```

This would've failed if they tried to upload it to https://packagist.org so it must be your own local repository?
